# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall

obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V3_MMI) += focaltech_v3_mmi.o
focaltech_v3_mmi-y := focaltech_core.o
focaltech_v3_mmi-y += focaltech_ex_fun.o
focaltech_v3_mmi-y += focaltech_ex_mode.o
focaltech_v3_mmi-y += focaltech_gesture.o
focaltech_v3_mmi-y += focaltech_esdcheck.o
focaltech_v3_mmi-y += focaltech_point_report_check.o
focaltech_v3_mmi-y += focaltech_flash.o
focaltech_v3_mmi-y += focaltech_i2c.o

ifneq ($(filter "ft3519",$(CONFIG_INPUT_FOCALTECH_MMI_IC_NAME)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_IC_NAME_FT3519
	focaltech_v3_mmi-y += focaltech_flash/focaltech_upgrade_ft5452i.o
endif

ifneq ($(filter "ft3518u",$(CONFIG_INPUT_FOCALTECH_MMI_IC_NAME)),)
	EXTRA_CFLAGS += -DCONFIG_FTS_IC_NAME_FT3518U
	focaltech_v3_mmi-y += focaltech_flash/focaltech_upgrade_ft3518u.o
endif

ccflags-$(CONFIG_INPUT_TOUCHSCREEN_MMI) += -DCONFIG_INPUT_TOUCHSCREEN_MMI
focaltech_v3_mmi-$(CONFIG_INPUT_TOUCHSCREEN_MMI) += focaltech_ts_mmi.o

ccflags-$(CONFIG_INPUT_FOCALTECH_MMI_ENABLE_DOUBLE_TAP) += -DFOCALTECH_SENSOR_EN